# Generated by Django 5.0.4 on 2024-05-02 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Priority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Attachments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=30)),
                ('file_extension', models.CharField(max_length=10)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.application')),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.categories'),
        ),
        migrations.CreateModel(
            name='CategorySupportAssociation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.categories')),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='support_employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.categorysupportassociation'),
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('patronymic', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20, unique=True)),
                ('phone', models.IntegerField(unique=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.department')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.position')),
            ],
        ),
        migrations.CreateModel(
            name='Credentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.people')),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='priority',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.priority'),
        ),
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.status'),
        ),
        migrations.CreateModel(
            name='SupportEmployers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.people')),
            ],
        ),
        migrations.AddField(
            model_name='categorysupportassociation',
            name='support_employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.supportemployers'),
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.people')),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.users'),
        ),
    ]
