# Generated by Django 5.0.4 on 2024-05-09 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Application',
            new_name='Ticket',
        ),
        migrations.RenameField(
            model_name='attachments',
            old_name='application',
            new_name='ticket',
        ),
    ]
