# Generated by Django 5.0.4 on 2024-05-11 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_rename_application_ticket_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtrDataTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CustomAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DataTypeTables',
            fields=[
                ('name', models.CharField(db_column='name', primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='CustomCategoryAttributes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.customattribute')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.categories')),
                ('dataType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.atrdatatypes')),
            ],
        ),
        migrations.AddField(
            model_name='atrdatatypes',
            name='dataTypeTable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.datatypetables'),
        ),
        migrations.CreateModel(
            name='IntDataType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.IntegerField()),
                ('attributeName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.customattribute')),
            ],
        ),
        migrations.CreateModel(
            name='StrDataType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=20)),
                ('attributeName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.customattribute')),
            ],
        ),
    ]
