# Generated by Django 5.0.4 on 2024-05-11 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_atrdatatypes_customattribute_datatypetables_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atrdatatypes',
            name='name',
        ),
        migrations.AddField(
            model_name='atrdatatypes',
            name='customAttribute',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='system.customattribute'),
            preserve_default=False,
        ),
    ]
