# Generated by Django 5.0.4 on 2024-05-11 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_remove_customcategoryattributes_datatype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strdatatype',
            name='attributeName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.customattribute', unique=True),
        ),
        migrations.CreateModel(
            name='ListDataType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.BooleanField()),
                ('attributeName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.customattribute')),
            ],
        ),
        migrations.CreateModel(
            name='TextDataType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField()),
                ('attributeName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.customattribute', unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='IntDataType',
        ),
    ]
