# Generated by Django 5.0.4 on 2024-05-11 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0006_alter_strdatatype_attributename_listdatatype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='support_employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='system.categorysupportassociation'),
        ),
    ]
