# Generated by Django 5.0.4 on 2024-05-17 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0008_alter_ticket_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listdatatype',
            name='attributeName',
        ),
        migrations.RemoveField(
            model_name='strdatatype',
            name='attributeName',
        ),
        migrations.RemoveField(
            model_name='textdatatype',
            name='attributeName',
        ),
        migrations.RemoveField(
            model_name='customcategoryattributes',
            name='atr',
        ),
        migrations.RemoveField(
            model_name='customcategoryattributes',
            name='category',
        ),
        migrations.DeleteModel(
            name='AtrDataTypes',
        ),
        migrations.DeleteModel(
            name='DataTypeTables',
        ),
        migrations.DeleteModel(
            name='ListDataType',
        ),
        migrations.DeleteModel(
            name='StrDataType',
        ),
        migrations.DeleteModel(
            name='TextDataType',
        ),
        migrations.DeleteModel(
            name='CustomAttribute',
        ),
        migrations.DeleteModel(
            name='CustomCategoryAttributes',
        ),
    ]
