# Generated by Django 5.0.4 on 2024-05-17 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0009_remove_listdatatype_attributename_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomAttributeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CustomAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('typeOfAttribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.customattributetype')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryCustomAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.categories')),
                ('custom_attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.customattributetype')),
            ],
        ),
        migrations.CreateModel(
            name='ListAttributeDataReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=30)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.customattribute')),
            ],
        ),
        migrations.CreateModel(
            name='ListAttributeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.customattribute')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.ticket')),
                ('data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.listattributedatareference')),
            ],
        ),
        migrations.CreateModel(
            name='StrAttributeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=30)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.customattribute')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.ticket')),
            ],
        ),
        migrations.CreateModel(
            name='TextAttributeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=250)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.customattribute')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.ticket')),
            ],
        ),
    ]
