# Generated by Django 5.0.4 on 2024-05-17 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0010_customattributetype_customattribute_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorycustomattribute',
            name='custom_attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.customattribute'),
        ),
    ]
