# Generated by Django 5.0.4 on 2024-05-19 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0011_alter_categorycustomattribute_custom_attribute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credentials',
            name='login',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.CreateModel(
            name='AutorizatedPeople',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=128)),
                ('expiration_date', models.DateTimeField()),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.people')),
            ],
        ),
    ]
