# Generated by Django 5.0.4 on 2024-05-20 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0013_alter_autorizatedpeople_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachments',
            name='file_extension',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='attachments',
            name='file_name',
            field=models.CharField(max_length=100),
        ),
    ]
