# Generated by Django 5.0.4 on 2024-05-20 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0014_alter_attachments_file_extension_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.people')),
            ],
        ),
    ]
