# Generated by Django 5.0.4 on 2024-05-23 18:07

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0015_supportadmin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autorizatedpeople',
            name='expiration_date',
            field=models.DateField(default=datetime.date(2024, 5, 28)),
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_name', models.CharField(default='12697d19-696c-44c8-a006-44e4b9ba4abc', max_length=36, unique=True)),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='system.ticket')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(default=datetime.datetime(2024, 5, 23, 21, 7, 55, 26082))),
                ('message', models.CharField(max_length=500)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.chat')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.people')),
            ],
        ),
    ]
